# Generated by Django 3.2.9 on 2022-01-25 18:04

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studpersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Age', models.CharField(max_length=3, null=True)),
                ('Dob', models.DateField(null=True)),
                ('Father_Name', models.CharField(max_length=25, null=True)),
                ('Mother_Name', models.CharField(max_length=25, null=True)),
                ('Mobile_Number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True)),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('Blood_Group', models.CharField(max_length=10, null=True)),
                ('Class', models.CharField(max_length=25, null=True)),
                ('Sec', models.CharField(max_length=25, null=True)),
            ],
        ),
    ]
